### ISSUE TITLE
problem start server.js

### ISSUE THREAD

**Issue by michelson** [maccman/juggernaut#15]
Hi , im trying juggernaut but when i start the server i get
 node server.js

node.js:50
    throw e;
    ^
TypeError: Object TԀ

Node version v0.3.0-pre

i followed this steps http://dailyjs.com/2010/09/13/juggernaut/

regards

**Comment by maccman** [comment]
Is redis running?

**Comment by michelson** [comment]
yes there is a redis daemon running

thanks

**Comment by manavid** [comment]
I'm having the same problem, I'm using git version of juggernut with redis-2.0.2.
Redis is running.

**Comment by maccman** [comment]
Follow the README instructions again - I've just updated them.

**Comment by manavid** [comment]
Hi,

I did run "npm install http://cl.ly/2dgx/content", still getting:
`
node.js:50
    throw e;
    ^
TypeError: Object 
`

**Comment by michelson** [comment]
i reinstalled all again , in a new machine, now i get this error: http://pastie.org/1194676

should i install socket.io with sudo ? in the documentation it recomend to not use sudo 

regards

**Comment by mperham** [comment]
Alex, I'm seeing the same error.

```
(M=c1a184) ~/git/juggernaut> node server.js 

node.js:63
    throw e;
    ^
Error: Cannot find module 'redis-client'
```

**Comment by maccman** [comment]
Mike, ping me when you're next available - we'll debug it over chat.

**Comment by maccman** [comment]
michelson , manavid, did you install node using brew?

**Comment by michelson** [comment]
Hi Macman, 

i installed node from source and i have the node v0.3.0-pre version

thanks

**Comment by manavid** [comment]
I macman,

I installed the node on my os x from source. I also did a separate installation on a linux box and having same problem.

Thanks

**Comment by c0d3x42** [comment]
Hi there,
I've been struggling with this error all morning too. i was using node-0.2.3, downgrading to 0.2.2 seems to work:
root@rails:/home/vince/juggernaut# node server.js
10 Oct 13:03:47 - socket.io ready - accepting connections
10 Oct 13:04:24 - Received: {"channels":["channel1"],"data":"Yo yo yo"}
10 Oct 13:04:24 - Publishing to channels: channel1 : Yo yo yo

**Comment by michelson** [comment]
c0d3x42, you are right , works with 0.2.2 , thanks

**Comment by romanenko** [comment]
MacBook-Pro-Michael-Romanenko:juggernaut michaelromanenko$ node server.js
The 'sys' module is now called 'util'. It should have a similar interface.

node.js:50
    throw e; // process.nextTick error, or 'error' event on first tick
    ^
Error: Cannot find module 'utils'
    at loadModule (node.js:229:13)
    at require (node.js:262:14)
    at Object.<anonymous> (/Users/michaelromanenko/code/juggernaut/lib/juggernaut/channel.js:2:13)
    at Module._compile (node.js:316:23)
    at Object..js (node.js:324:12)
    at Module.load (node.js:250:25)
    at loadModule (node.js:237:12)
    at require (node.js:262:14)
    at Object.<anonymous> (/Users/michaelromanenko/code/juggernaut/lib/juggernaut/publish.js:4:15)
    at Module._compile (node.js:316:23)

On my OSX, nodejs 0.3.0pre, followed your instructions in README

**Comment by maccman** [comment]
Ok, can you swap out sys with util in your repo to see if it works. If they have the same interface, it should be fairly simple to work with both.

**Comment by jntn** [comment]
I got the same error as perfecto. But it got nothing to do with sys changing name to util, it's the utils package in channel.js that is the culprit.

**Comment by maccman** [comment]
jntn, can you elaborate? What's the fix?

**Comment by muthiafi** [comment]
i still got the same problem
node.js:50
    throw e; // process.nextTick error, or 'error' event on first tick
    ^
TypeError: Object

and i follow the latest installation readme.
still no solution?

**Comment by maccman** [comment]
Ok, all fixed. I've patched redis-client and node-static. I've also vendored them in submodules - so you don't need npm.

Have a look at the updated README.

**Comment by variousred** [comment]
Following the latest instructions, I'm getting the error

`Cannot find module 'redis-client'`

when running node server.js

i tried node-0.2.4, as well as node-0.2.2

**Comment by yuvadm** [comment]
Same here.

I'm getting `Error: Cannot find module 'redis-client'`
on a clean Ubuntu 10.10 image with node v0.2.5

**Comment by ryenski** [comment]
I had all of the problems listed above. Make sure you: 
- run node-v.2.x - v3.x may not work
- clone juggernaut with recursive. If you don't, it probably won't work.

**Comment by gipnokote** [comment]
Followed readme instructuions on Ubuntu 10.10, node v. 0.3.1:

```
root@ubuntu:~/rails/juggernaut# node server.js 

node.js:58
throw e; // process.nextTick error, or 'error' event on first tick
^
Error: Cannot find module 'utils'
at resolveModuleFilename (node.js:251:13)
at loadModule (node.js:213:20)
at require (node.js:277:14)
at Object.<anonymous> (/home/andy/rails/juggernaut/lib/juggernaut/channel.js:2:13)
at Module._compile (node.js:332:30)
at Object..js (node.js:340:12)
at Module.load (node.js:265:25)
at loadModule (node.js:237:12)
at require (node.js:277:14)
at Object.<anonymous> (/home/andy/rails/juggernaut/lib/juggernaut/publish.js:4:15)
```

commented out the second line in channel.js - no more errors:

```
root@ubuntu:~/rails/juggernaut# node server.js 
2 Dec 01:15:58 - socket.io ready - accepting connections
```

wonder if 'utils' is really needed..

**Comment by maccman** [comment]
Thanks, fix committed.
